import shoes1 from './images/m-one.jpg';
import shoes2 from './images/m-two.jpg';
import shoes3 from './images/m-three.jpg';
import shoes4 from './images/m-four.jpg';
import shoes5 from './images/m-five.jpg';
import shoes6 from './images/m-six.jpg';
import shoes7 from './images/m-seven.jpg';
import shoes8 from './images/m-eight.jpg';
import shoes9 from './images/m-nine.jpg';
import shoes10 from './images/m-ten.jpg';
import shoes11 from './images/m-eleven.jpg';
import shoes12 from './images/m-twelve.jpg';
import shoes13 from './images/m-thirteen.jpg';
import shoes14 from './images/m-fourteen.jpg';
import shoes15 from './images/m-fifteen.jpg';
import shoes16 from './images/m-sixteen.jpg';
import shoes17 from './images/m-seventeen.jpg';
import shoes18 from './images/m-eighteen.jpg';
import shoes19 from './images/m-nineteen.jpg';
import shoes20 from './images/m-twenty.jpg';
import shoes21 from './images/m-twenty-one.jpg';
import shoes22 from './images/m-twenty-two.jpg';
import shoes23 from './images/m-twenty-three.jpg';
import shoes24 from './images/m-twenty-four.jpg';
import shoes25 from './images/m-twenty-five.jpg';
import shoes26 from './images/m-twenty-six.jpg';
import shoes27 from './images/m-twenty-seven.jpg';
import shoes28 from './images/m-twenty-eight.jpg';
import shoes29 from './images/m-twenty-nine.jpg';
import shoes30 from './images/m-thirty.jpg';

export const dataItems = [
    {
        id: 1,
        image: shoes1,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Коричневый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 5400,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 2,
        image: shoes2,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Бордо',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 3200,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 3,
        image: shoes3,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Синий',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 3800,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 4,
        image: shoes4,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Бежевый',
        material: 'Нубук',
        base: 'Полиуретан',
        price: 2300,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 5,
        image: shoes5,
        title: 'Женские полусапоги',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Серый',
        material: 'Натуральная замша',
        base: 'Резина',
        price: 4900,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 6,
        image: shoes6,
        title: 'Женские полусапоги',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Резина',
        price: 5500,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 7,
        image: shoes7,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Синий',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 4000,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 8,
        image: shoes8,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Коричневый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 4000,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 9,
        image: shoes9,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 3800,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 10,
        image: shoes10,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Серый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 2700,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 11,
        image: shoes11,
        title: 'Женские ботинки',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Темно-зеленый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 4800,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 12,
        image: shoes12,
        title: 'Женские ботинки',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Серый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 6100,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 13,
        image: shoes13,
        title: 'Женские ботинки',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Резина',
        price: 4500,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 14,
        image: shoes14,
        title: 'Женские ботинки',
        filter: 'women',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Резина',
        price: 3700,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 15,
        image: shoes15,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Бежевый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 3300,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 16,
        image: shoes16,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Бежевый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 3300,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 17,
        image: shoes17,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Белый',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 3500,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 18,
        image: shoes18,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Серый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 3800,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 19,
        image: shoes19,
        title: 'Мужские лоферы',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 4800,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 20,
        image: shoes20,
        title: 'Мужские туфли',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 4400,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 21,
        image: shoes21,
        title: 'Мужские ботинки',
        filter: 'men',
        season: 'Весна, Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 5600,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 22,
        image: shoes22,
        title: 'Мужские ботинки',
        filter: 'men',
        season: 'Зима',
        size: '40 - 45',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 5000,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 23,
        image: shoes23,
        title: 'Мужские лоферы',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Бежевый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 3400,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 24,
        image: shoes24,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Черный',
        material: 'Натуральная кожа',
        base: 'Полиуретан',
        price: 5200,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 25,
        image: shoes25,
        title: 'Женские кеды',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Черный',
        material: 'Текстиль',
        base: 'Полиуретан',
        price: 2000,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 26,
        image: shoes26,
        title: 'Мужские кеды',
        filter: 'men',
        season: 'Весна - Осень',
        size: '40 - 45',
        color: 'Белый',
        material: 'Натуральная кожа',
        base: 'Резина',
        price: 5200,
        show: false,
        size1: 40,
        size2: 41,
        size3: 42,
        size4: 43,
        size5: 44,
        size6: 45
    },
    {
        id: 27,
        image: shoes27,
        title: 'Женские босоножки',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Желтый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 4300,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 28,
        image: shoes28,
        title: 'Женские босоножки',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Пудра',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 3100,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 29,
        image: shoes29,
        title: 'Женские босоножки',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Пудра',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 2800,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    },
    {
        id: 30,
        image: shoes30,
        title: 'Женские босоножки',
        filter: 'women',
        season: 'Весна - Осень',
        size: '35 - 40',
        color: 'Коричневый',
        material: 'Натуральная замша',
        base: 'Полиуретан',
        price: 2800,
        show: false,
        size1: 35,
        size2: 36,
        size3: 37,
        size4: 38,
        size5: 39,
        size6: 40
    }
];
